---
# Description: Add the device to the site
# Modules Used: inventory_workflow_manager.py
# Dependencies: None
# Tags: Add the device to inventory, Add the device, Find the device


- name: Add the device to the inventory
  cisco.dnac.inventory_workflow_manager:
    dnac_host: "{{dnac_host}}"
    dnac_username: "{{dnac_username}}"
    dnac_password: "{{dnac_password}}"
    dnac_verify: "{{dnac_verify}}"
    dnac_port: "{{dnac_port}}"
    dnac_version: "{{dnac_version}}"
    dnac_debug: "{{dnac_debug}}"
    dnac_log_level: "{{dnac_log_level}}"
    dnac_log: "{{dnac_log}}"
    state: merged
    config:
    - cli_transport: ssh
      compute_device: False
      password: Test@123
      enable_password: Test@1234
      extended_discovery_info: test
      http_username: "testuser"
      http_password: "test"
      http_port: "443"
      http_secure: False
      ip_address_list: ["1.1.1.1", "2.2.2.2"]
      netconf_port: 830
      snmp_auth_passphrase: "Lablab@12"
      snmp_auth_protocol: SHA
      snmp_mode: AUTHPRIV
      snmp_priv_passphrase: "Lablab@123"
      snmp_priv_protocol: AES256
      snmp_retry: 3
      snmp_timeout: 5
      snmp_username: v3Public
      snmp_version: v3
      type: NETWORK_DEVICE
      username: cisco
