---
# Description: Create SNMP Read and SNMP Write credential
# Modules Used: device_credential_workflow_manager.py
# Dependencies: None
# Tags: Create SNMP Read and SNMP Write credential, Create Global Credentails SNMP Read and SNMP Write, Create SNMP Read and SNMP Write


- name: Create an SNMP Read and SNMP Write credential
  cisco.dnac.device_credential_workflow_manager:
    dnac_host: "{{dnac_host}}"
    dnac_username: "{{dnac_username}}"
    dnac_password: "{{dnac_password}}"
    dnac_verify: "{{dnac_verify}}"
    dnac_port: "{{dnac_port}}"
    dnac_version: "{{dnac_version}}"
    dnac_debug: "{{dnac_debug}}"
    dnac_log_level: "{{dnac_log_level}}"
    dnac_log: "{{dnac_log}}"
    state: merged
    config:
    - global_credential_details:
        snmp_v2c_read:
        - description: SNMPv2c Read1
          read_community: '123456'
        snmp_v2c_write:
        - description: SNMPv2c Write1
          write_community: '123456'
