---
# Description: Create a new Building site
# Modules Used: site_workflow_manager.py
# Dependencies: Create floor
# Tags: Create Building, Building, New Building, Create Building under area

- name: Create a new Building site
  cisco.dnac.site_workflow_manager:
    dnac_host: "{{dnac_host}}"
    dnac_username: "{{dnac_username}}"
    dnac_password: "{{dnac_password}}"
    dnac_verify: "{{dnac_verify}}"
    dnac_port: "{{dnac_port}}"
    dnac_version: "{{dnac_version}}"
    dnac_debug: "{{dnac_debug}}"
    dnac_log_level: "{{dnac_log_level}}"
    dnac_log: "{{dnac_log}}"
    state: merged
    config:
    - site:
        building:
          name: Mantri Square
          parent_name: Global/India-Test/Bangalore
          address: Bengaluru, Karnataka, India
          latitude: 18.969910
          longitude: 20.597960
          country: India
      site_type: building
