---
# Description: Delete CLI credential
# Modules Used: device_credential_workflow_manager.py
# Dependencies: None
# Tags: Delete CLI credential, Delete Global Credentails CLI, Delete CLI

- name: Delete an CLI credential
  cisco.dnac.device_credential_workflow_manager:
    dnac_host: "{{dnac_host}}"
    dnac_username: "{{dnac_username}}"
    dnac_password: "{{dnac_password}}"
    dnac_verify: "{{dnac_verify}}"
    dnac_port: "{{dnac_port}}"
    dnac_version: "{{dnac_version}}"
    dnac_debug: "{{dnac_debug}}"
    dnac_log_level: "{{dnac_log_level}}"
    dnac_log: "{{dnac_log}}"
    state: deleted
    config:
    - global_credential_details:
        cli_credential:
        - description: CLI1
          username: cli1
