---
# Description: Delete the device to the site
# Modules Used: inventory_workflow_manager.py
# Dependencies: None
# Tags: Delete the device to inventory, Delete the device, Remove the device, Remove the device from the inventory


- name: Delete the device to the inventory
  cisco.dnac.inventory_workflow_manager:
    dnac_host: "{{dnac_host}}"
    dnac_username: "{{dnac_username}}"
    dnac_password: "{{dnac_password}}"
    dnac_verify: "{{dnac_verify}}"
    dnac_port: "{{dnac_port}}"
    dnac_version: "{{dnac_version}}"
    dnac_debug: "{{dnac_debug}}"
    dnac_log_level: "{{dnac_log_level}}"
    dnac_log: "{{dnac_log}}"
    state: deleted
    config:
    - ip_address_list: ["1.1.1.1", "2.2.2.2"]
