---
# Description: Delete SNMP Read and SNMP Write credential
# Modules Used: device_credential_workflow_manager.py
# Dependencies: None
# Tags: Delete SNMP Read and SNMP Write credential, Delete Global Credentails SNMP Read and SNMP Write, Delete SNMP Read and SNMP Write


- name: Delete an SNMP Read and SNMP Write credential
  cisco.dnac.device_credential_workflow_manager:
    dnac_host: "{{dnac_host}}"
    dnac_username: "{{dnac_username}}"
    dnac_password: "{{dnac_password}}"
    dnac_verify: "{{dnac_verify}}"
    dnac_port: "{{dnac_port}}"
    dnac_version: "{{dnac_version}}"
    dnac_debug: "{{dnac_debug}}"
    dnac_log_level: "{{dnac_log_level}}"
    dnac_log: "{{dnac_log}}"
    state: deleted
    config:
    - global_credential_details:
        snmp_v2c_read:
        - description: SNMPv2c Read1
        snmp_v2c_write:
        - description: SNMPv2c Write1
